CREATE TABLE IF NOT EXISTS Article (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Sku VARCHAR(50) NOT NULL UNIQUE,
    Name VARCHAR(255) NOT NULL,
    MinQuantity INT NOT NULL DEFAULT 0,
    CreatedAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);

CREATE TABLE IF NOT EXISTS Stocks (
    ArticleId INT NOT NULL,
    Quantity INT NOT NULL DEFAULT 0,
    UpdatedAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ArticleId),
    Constraint fk_stock<-article FOREIGN KEY (ArticleId) REFERENCES Article(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Booking (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ArticleId INT NOT NULL,
    Quantity INT NOT NULL,
    Delta INT NOT NULL,
    Reason VARCHAR(255) NOT NULL,
    CreatedAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    Constraint fk_booking_article FOREIGN KEY (ArticleId) REFERENCES Article(Id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS ix_booking_article_created ON Booking (ArticleId, CreatedAT);